### ISSUE TITLE
Pseudo Selector API Proposal

### ISSUE THREAD

**Issue by jaredpalmer** [petehunt/jsxstyle#28]
What if jsxstyle's CSS extractor looked out for special reserved prop prefixes such as `hover`, `focus`, `active` (for starters) and added the psuedo selector declaration accordingly. I'm aware that this would not bring jsxstyle to full parity with CSS pseudo-selectors, but it would solve ~80% the challenges with buttons and inputs.

```javascript
// component.js
<Flex borderColor="red" hoverBorderColor="blue" />
```

```css
/* extracted css */
.f12345_0 {
  border-color: red;
}
.f12345_0:hover {
  border-color: blue;
}
```
